# Generated by Django 4.2.4 on 2024-09-05 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appoinment",
            old_name="doctor",
            new_name="Doctor",
        ),
        migrations.RenameField(
            model_name="appoinment",
            old_name="patient",
            new_name="Patient",
        ),
    ]
